version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/probono-backend
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 90
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 90
