# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release" ]

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: github-actions-deploy-s3bucket
  AWS_CODE_DEPLOY_APPLICATION: Application-CodeDeploy
  AWS_CODE_DEPLOY_GROUP: Deployment-Group

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    #    services:
    #      mysql:
    #        image: mysql:8.0
    #        ports:
    #          - 3306:3306
    #        env:
    #          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #          MYSQL_DATABASE: probono_db

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          #          host port: 3800 # Optional, default value is 3306. The port of host
          #          container port: 3307 # Optional, default value is 3306. The port of container
          #          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          #          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'probono_db' # Optional, default value is "test". The specified database which will be create
          #          mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'GCC' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.DB_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"

      - uses: actions/checkout@v4
#      - run: touch ./src/main/resources/application-prod.properties
#      - run: echo "${{ secrets.APPLICATION }}" >> ./src/main/resources/application-prod.properties
#      - run: echo "${{ secrets.JWT_SECRET }}" >> ./src/main/resources/application-prod.properties
#      - run: echo "${{ secrets.ADMIN_ACCOUNT }}" >> ./src/main/resources/application-prod.properties
#      - run: echo "${{ secrets.PROD_DB_URL }}" >> ./src/main/resources/application-prod.properties
#
#      - run: echo "spring.sql.init.mode=never" >> ./src/main/resources/application-prod.properties
#      - run: echo "logging.level.com.zaxxer.hikari=DEBUG" >> ./src/main/resources/application-prod.properties

      - name: SSH into EC2-A and run deploy.sh
        uses: appleboy/ssh-action@v1.0.0 
        with:
          host: ${{ secrets.WAS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.WAS_EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/probono-backend/deploy
            chmod +x deploy.sh
            ./deploy.sh

